### ISSUE TITLE
大佬，图形验证出现了一点问题

### ISSUE THREAD

**Issue by dream432523523** [icepage/AutoUpdateJdCookie#10]
2024-06-25 21:57:59.332 | INFO     | __main__:auto_move_slide:53 - 第1次尝试自动移动滑块中...
2024-06-25 21:58:07.298 | INFO     | __main__:auto_move_slide:53 - 第2次尝试自动移动滑块中...
2024-06-25 21:58:12.687 | INFO     | __main__:auto_move_slide:53 - 第3次尝试自动移动滑块中...
2024-06-25 21:58:18.192 | INFO     | __main__:auto_move_slide:53 - 第4次尝试自动移动滑块中...
2024-06-25 21:58:24.028 | INFO     | __main__:auto_move_slide:53 - 第5次尝试自动移动滑块中...
2024-06-25 21:58:31.056 | INFO     | __main__:auto_shape:88 - 第1次自动识别形状中...
2024-06-25 21:58:32.190 | INFO     | __main__:auto_shape:158 - 已找到图形,点击中......
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\AutoUpdateJdCookie-main\main.py", line 231, in get_jd_pt_key
    await auto_shape(page, retry_times=30)
  File "C:\Users\Administrator\Desktop\AutoUpdateJdCookie-main\main.py", line 162, in auto_shape
    center_x, center_y = get_shape_location_by_type(background_img_path, shape_type)
  File "C:\Users\Administrator\Desktop\AutoUpdateJdCookie-main\utils\tools.py", line 194, in get_shape_location_by_type
    contours, hierarchy = cv2.findContours(imgCanny, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)  # 寻找轮廓点
ValueError: too many values to unpack (expected 2)
2024-06-25 21:58:33.525 | ERROR    | __main__:main:333 - 获取pt_key失败

直接就跳出来了，没有完成图形识别点击的任务，而且模拟滑动之后必出图形。不太懂是咋回事，希望大佬有时间抽空看一下

**Comment by dream432523523** [comment]
> 2024-06-25 21:57:59.332 | INFO | **main**:auto_move_slide:53 - 第1次尝试自动移动滑块中... 2024-06-25 21:58:07.298 | INFO | **main**:auto_move_slide:53 - 第2次尝试自动移动滑块中... 2024-06-25 21:58:12.687 | INFO | **main**:auto_move_slide:53 - 第3次尝试自动移动滑块中... 2024-06-25 21:58:18.192 | INFO | **main**:auto_move_slide:53 - 第4次尝试自动移动滑块中... 2024-06-25 21:58:24.028 | INFO | **main**:auto_move_slide:53 - 第5次尝试自动移动滑块中... 2024-06-25 21:58:31.056 | INFO | **main**:auto_shape:88 - 第1次自动识别形状中... 2024-06-25 21:58:32.190 | INFO | **main**:auto_shape:158 - 已找到图形,点击中...... Traceback (most recent call last): File "C:\Users\Administrator\Desktop\AutoUpdateJdCookie-main\main.py", line 231, in get_jd_pt_key await auto_shape(page, retry_times=30) File "C:\Users\Administrator\Desktop\AutoUpdateJdCookie-main\main.py", line 162, in auto_shape center_x, center_y = get_shape_location_by_type(background_img_path, shape_type) File "C:\Users\Administrator\Desktop\AutoUpdateJdCookie-main\utils\tools.py", line 194, in get_shape_location_by_type contours, hierarchy = cv2.findContours(imgCanny, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE) # 寻找轮廓点 ValueError: too many values to unpack (expected 2) 2024-06-25 21:58:33.525 | ERROR | **main**:main:333 - 获取pt_key失败
> 
> 直接就跳出来了，没有完成图形识别点击的任务，而且模拟滑动之后必出图形。不太懂是咋回事，希望大佬有时间抽空看一下
