### ISSUE TITLE
请问我的在windows下运行，提示这个报错是哪里配置问题呢

### ISSUE THREAD

**Issue by 5jwoj** [icepage/AutoUpdateJdCookie#33]
python main.py
Traceback (most recent call last):
File "C:\Users\z\Desktop\JD\other\main.py", line 5, in
from config import (
File "C:\Users\z\Desktop\JD\other\config.py", line 6
"force_update": "True"
^
SyntaxError: invalid syntax

**Comment by icepage** [comment]
语法错误，上一行是否少了个逗号
