### ISSUE TITLE
我这个怎么没有地方填写验证码啊！是哪里没操作对

### ISSUE THREAD

**Issue by sd462355991** [icepage/AutoUpdateJdCookie#41]
# JD用户信息
user_datas = {
    "1598隐私68": {
        "password": "A98隐私1a",
        "pt_pin": "jd_4af2隐私06",
        "sms_func": "manual_input",
        "force_update": True
    },
    "1814隐私71": {
        "password": "A982隐私1a",
        "pt_pin": "1814隐私1_p",
        "sms_func": "manual_input",
        "force_update": True

# 滑块验证码的偏差, 如果一直滑过了, 或滑不到, 可以调节下
slide_difference = 10

# 是否自动识别移动滑块，有时不准，就关掉吧
auto_move = True

# 是否自动形状验证码识别，有时不准，就关掉吧
auto_shape_recognition = True

# 定时器
cron_expression = "35 5,11,17,23 * * *"

# 浏览器是否开启无头模式，即是否展示整个登录过程
headless = True

# 是否开启发消息
is_send_msg = True
# 更新成功后是否发消息的开关
is_send_success_msg = True
# 更新失败后是否发消息的开关
is_send_fail_msg = True
# 配置发送地址
send_info = {
    "send_wecom": [
	    "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=ac隐私隐私隐私bef"
    ],
    "send_webhook": [
    ],
    "send_dingtalk": [
    ],
    "send_feishu": [
    ]
}

# sms_func为填写验信验证码的模式，有3种可选，如下：
# no 关闭短信验证码识别
# manual_input 手动在终端输入验证码
# webhook 调用api获取验证码,可实现全自动填写验证码
sms_func = "manual_input"
sms_webhook = "https://127.0.0.1:3000/getCode"

2024-10-21 09:01:12.024 | INFO     | __main__:auto_shape:134 - 第7次自动识别形状中...
2024-10-21 09:01:13.031 | INFO     | __main__:auto_shape:203 - 开始文字识别,点击中......
2024-10-21 09:01:14.248 | INFO     | __main__:auto_shape:251 - 文字识别失败,刷新中......
2024-10-21 09:01:16.483 | INFO     | __main__:auto_shape:134 - 第8次自动识别形状中...
2024-10-21 09:01:17.500 | INFO     | __main__:auto_shape:203 - 开始文字识别,点击中......
2024-10-21 09:01:18.454 | INFO     | __main__:auto_shape:251 - 文字识别失败,刷新中......
2024-10-21 09:01:21.360 | INFO     | __main__:auto_shape:134 - 第9次自动识别形状中...
2024-10-21 09:01:22.404 | INFO     | __main__:auto_shape:203 - 开始文字识别,点击中......
2024-10-21 09:01:35.260 | INFO     | __main__:auto_shape:134 - 第10次自动识别形状中...
2024-10-21 09:01:38.265 | INFO     | __main__:auto_shape:140 - 未找到形状图,退出识别状态
2024-10-21 09:01:38.294 | INFO     | __main__:sms_recognition:322 - 发送短信验证码成功
请输入验证码：Traceback (most recent call last):
  File "/app/main.py", line 412, in get_jd_pt_key
    await sms_recognition(page, user)
  File "/app/main.py", line 329, in sms_recognition
    verification_code = inputimeout(prompt="请输入验证码：", timeout=60)
  File "/usr/local/lib/python3.10/site-packages/inputimeout/inputimeout.py", line 24, in posix_inputimeout
    sel.register(sys.stdin, selectors.EVENT_READ)
  File "/usr/local/lib/python3.10/selectors.py", line 360, in register
    self._selector.register(key.fd, poller_events)
PermissionError: [Errno 1] Operation not permitted
2024-10-21 09:01:38.423 | ERROR    | __main__:main:517 - 获取pt_key失败
2024-10-21 09:01:38.687 | INFO     | utils.tools:send_msg:332 - 发送消息到 https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=ac3隐私隐私bef, 响应:{'errcode': 0, 'errmsg': 'ok'}
root@YQF:~# 

指令是用这个：
docker run -v /volume1/docker/AutoUpdateJdCookie-main/config.py:/app/config.py icepage/aujc:latest python main.py

config.py已经设置了
manual_input

是哪个设置不对，还是什么问题？

**Comment by 5jwoj** [comment]
你可以在web里输入验证码，也可以在终端那个框里

**Comment by sd462355991** [comment]
> 你可以在web里输入验证码，也可以在终端那个框里

我是用docker

> 你可以在web里输入验证码，也可以在终端那个框里

我是docker容器的，没有web吧，ssh软件没有可以输入的窗口
