### ISSUE TITLE
ssh软件：发送短信验证码成功，但是自己主动跳出来。根本没地方给你填写验证码。

### ISSUE THREAD

**Issue by sd462355991** [icepage/AutoUpdateJdCookie#43]
2024-10-21 17:40:49.944 | INFO     | __main__:get_ql_api:439 - 开始获取QL登录态......
2024-10-21 17:40:49.945 | INFO     | __main__:get_ql_api:445 - 使用client_id和client_secret登录......
2024-10-21 17:40:50.011 | INFO     | __main__:get_ql_api:449 - client_id和client_secret正常可用......
2024-10-21 17:40:50.034 | INFO     | __main__:main:489 - 获取环境变量成功
2024-10-21 17:40:51.270 | INFO     | __main__:main:514 - 开始更新1805隐私04
2024-10-21 17:41:01.949 | INFO     | __main__:auto_move_slide:73 - 第1次尝试自动移动滑块中...
2024-10-21 17:41:09.855 | INFO     | __main__:auto_move_slide:73 - 第2次尝试自动移动滑块中...
2024-10-21 17:41:12.873 | INFO     | __main__:auto_move_slide:79 - 未找到小图,退出移动滑块
2024-10-21 17:41:14.429 | INFO     | __main__:auto_shape:134 - 第1次自动识别形状中...
2024-10-21 17:41:15.374 | INFO     | __main__:auto_shape:203 - 开始文字识别,点击中......
2024-10-21 17:41:16.506 | INFO     | __main__:auto_shape:251 - 文字识别失败,刷新中......
2024-10-21 17:41:20.088 | INFO     | __main__:auto_shape:134 - 第2次自动识别形状中...
2024-10-21 17:41:21.000 | INFO     | __main__:auto_shape:203 - 开始文字识别,点击中......
2024-10-21 17:41:22.330 | INFO     | __main__:auto_shape:251 - 文字识别失败,刷新中......
2024-10-21 17:41:24.768 | INFO     | __main__:auto_shape:134 - 第3次自动识别形状中...
2024-10-21 17:41:25.811 | INFO     | __main__:auto_shape:203 - 开始文字识别,点击中......
2024-10-21 17:41:36.786 | INFO     | __main__:auto_shape:134 - 第4次自动识别形状中...
2024-10-21 17:41:39.793 | INFO     | __main__:auto_shape:140 - 未找到形状图,退出识别状态
2024-10-21 17:41:40.811 | INFO     | __main__:get_jd_pt_key:411 - 开始短信验证码识别环节
2024-10-21 17:41:40.812 | INFO     | __main__:sms_recognition:313 - 点击【获取验证码】中
2024-10-21 17:41:41.945 | INFO     | __main__:auto_move_slide:73 - 第1次尝试自动移动滑块中...
2024-10-21 17:41:49.407 | INFO     | __main__:auto_move_slide:73 - 第2次尝试自动移动滑块中...
2024-10-21 17:41:52.411 | INFO     | __main__:auto_move_slide:79 - 未找到小图,退出移动滑块
2024-10-21 17:41:52.869 | INFO     | __main__:auto_shape:134 - 第1次自动识别形状中...
2024-10-21 17:41:53.953 | INFO     | __main__:auto_shape:203 - 开始文字识别,点击中......
2024-10-21 17:41:55.153 | INFO     | __main__:auto_shape:251 - 文字识别失败,刷新中......
2024-10-21 17:41:58.616 | INFO     | __main__:auto_shape:134 - 第2次自动识别形状中...
2024-10-21 17:41:59.724 | INFO     | __main__:auto_shape:203 - 开始文字识别,点击中......
2024-10-21 17:42:01.194 | INFO     | __main__:auto_shape:251 - 文字识别失败,刷新中......
2024-10-21 17:42:04.941 | INFO     | __main__:auto_shape:134 - 第3次自动识别形状中...
2024-10-21 17:42:05.903 | INFO     | __main__:auto_shape:203 - 开始文字识别,点击中......
2024-10-21 17:42:06.937 | INFO     | __main__:auto_shape:251 - 文字识别失败,刷新中......
2024-10-21 17:42:09.866 | INFO     | __main__:auto_shape:134 - 第4次自动识别形状中...
2024-10-21 17:42:11.085 | INFO     | __main__:auto_shape:203 - 开始文字识别,点击中......
2024-10-21 17:42:12.069 | INFO     | __main__:auto_shape:251 - 文字识别失败,刷新中......
2024-10-21 17:42:15.799 | INFO     | __main__:auto_shape:134 - 第5次自动识别形状中...
2024-10-21 17:42:16.745 | INFO     | __main__:auto_shape:203 - 开始文字识别,点击中......
2024-10-21 17:42:17.768 | INFO     | __main__:auto_shape:251 - 文字识别失败,刷新中......
2024-10-21 17:42:20.362 | INFO     | __main__:auto_shape:134 - 第6次自动识别形状中...
2024-10-21 17:42:21.397 | INFO     | __main__:auto_shape:203 - 开始文字识别,点击中......
2024-10-21 17:42:33.357 | INFO     | __main__:auto_shape:134 - 第7次自动识别形状中...
2024-10-21 17:42:36.363 | INFO     | __main__:auto_shape:140 - 未找到形状图,退出识别状态
2024-10-21 17:42:36.388 | INFO     | __main__:sms_recognition:322 - 发送短信验证码成功
Traceback (most recent call last):
  File "/app/main.py", line 412, in get_jd_pt_key
    await sms_recognition(page, user)
  File "/app/main.py", line 329, in sms_recognition
    verification_code = inputimeout(prompt="请输入验证码：", timeout=60)
  File "/usr/local/lib/python3.10/site-packages/inputimeout/inputimeout.py", line 24, in posix_inputimeout
    sel.register(sys.stdin, selectors.EVENT_READ)
  File "/usr/local/lib/python3.10/selectors.py", line 360, in register
    self._selector.register(key.fd, poller_events)
PermissionError: [Errno 1] Operation not permitted
2024-10-21 17:42:36.511 | ERROR    | __main__:main:517 - 获取pt_key失败
2024-10-21 17:42:36.851 | INFO     | utils.tools:send_msg:332 - 发送消息到 https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=ac3e87e8-6隐私隐私隐私ef, 响应:{'errcode': 0, 'errmsg': 'ok'}
请输入验证码：
root@YQF:~# 发送短信验证码成功，但是自己主动跳出来。根本没地方给你填写验证码。

直接用下面这个命令更新
docker run -v /volume1/docker/AutoUpdateJdCookie-main/config.py:/app/config.py icepage/aujc:latest python main.py

finalshell软件ssh操作，我以为是软件问题，换putty也是这个问题。
发送短信验证码成功，但是自己主动跳出来。根本没地方给你填写验证码。

**Comment by icepage** [comment]
docker是加上-i 参数，由系统分配终端。我更新下文档说明 @sd462355991
