### ISSUE TITLE
作者可以帮忙看看疑惑吗？pushplus的webhook吗?sms这个有点不懂怎么配置？pin是不是这样操作？

### ISSUE THREAD

**Issue by corsgoo** [icepage/AutoUpdateJdCookie#50]
# 配置发送地址
send_info = {
    "send_wecom": [
    ],
    "send_webhook": [https://www.pushplus.plus/send?token=1 XXXXXXX3
    ],
    "send_dingtalk": [
    ],
    "send_feishu": [
博主，这个是不是就这样填一串其他就不用写了哇？这个地方是拿来推送通知吧？比如是否更新或者失败。
 "send_wecom": [这个不用管吧？

sms_webhook = "https://127.0.0.1:3000/getCode"这个我看了下解释想求问下这个是应用流程是不是，docker安装那个SmsCodeWebook，然后需要自己安装SmsForwarder) 监听手机短信，这个软件是安装在手机上自动监听验证码并在局域网转发，手机是需要连接跟AutoUpdateJdCookie。SmsCodeWebhook都在同一个局域网可以互访。SmsForwarder把短信转发到：
curl -X POST 'http://127.0.0.1:8000/api/getCode  比如这个端口。
就自动填写到AutoUpdateJdCookie里面了呢？我理解是否正确。我还在摸索尝试部署。

**Comment by corsgoo** [comment]
pt pin是需要自己去先抓取账号的【pt pin填进去吧】  },
    "13500000002": {
        "password": "123456",
        "pt_pin": "123456",
我看这里配置的地方就要求直接填写了

**Comment by corsgoo** [comment]
Traceback (most recent call last):
  File "/app/main.py", line 5, in <module>
    from config import (
  File "/app/config.py", line 62
    "send_webhook": [https://www.pushplus.plus/send?token=16504ff1800a4073a8540a4ca6d5d333/
                                                              ^
SyntaxError: invalid decimal literal

运行一直这样

**Comment by corsgoo** [comment]
我找了gpt和百度了很久，加上实操还是没办法正常运行，门槛确实高哦，作者是否可以尝试从0录制一个视频放到自己的网盘，到时候分享做一个视频教程哇。。。我现在已经搞不定了。。
