### ISSUE TITLE
第一次一个号成功了，后来添加了几个号就一直出错了

### ISSUE THREAD

**Issue by jamesyoung233** [icepage/AutoUpdateJdCookie#52]
Traceback (most recent call last):
  File "/app/main.py", line 464, in get_jd_pt_key
    await page.wait_for_selector('#msShortcutMenu', state='visible', timeout=120000)
  File "/usr/local/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 7999, in wait_for_selector
    await self._impl_obj.wait_for_selector(
  File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_page.py", line 397, in wait_for_selector
    return await self._main_frame.wait_for_selector(**locals_to_params(locals()))
  File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 323, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
  File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Page.wait_for_selector: Timeout 120000ms exceeded.
Call log:
waiting for locator("#msShortcutMenu") to be visible

**Comment by icepage** [comment]
不成功的号是的QQ号吗？

**Comment by jamesyoung233** [comment]
是我的问题，手机号位数搞错了，已发现
