### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by allonmymind** [icepage/AutoUpdateJdCookie#60]
确定config.py格式正确，不知道为何一直报错
root@Ubuntu:/app/autojd# docker run -i -v $PWD/config.py:/app/config.py icepage/aujc:latest python main.py
2024-10-31 09:38:37.826 | INFO     | __main__:get_ql_api:500 - 开始获取QL登录态......
2024-10-31 09:38:37.826 | INFO     | __main__:get_ql_api:506 - 使用client_id和client_secret登录......
2024-10-31 09:38:39.020 | INFO     | __main__:get_ql_api:510 - client_id和client_secret正常可用......
2024-10-31 09:38:40.320 | INFO     | __main__:main:550 - 获取环境变量成功
Traceback (most recent call last):
  File "/app/main.py", line 560, in main
    forbidden_users = [x for x in user_info if x['name'] == 'JD_COOKIE' and (x['status'] == 1 or x['value'].rstrip(';').split('pt_pin=')[1] in force_update_pt_pins)]
  File "/app/main.py", line 560, in <listcomp>
    forbidden_users = [x for x in user_info if x['name'] == 'JD_COOKIE' and (x['status'] == 1 or x['value'].rstrip(';').split('pt_pin=')[1] in force_update_pt_pins)]
IndexError: list index out of range
root@Ubuntu:/app/autojd#

**Comment by allonmymind** [comment]
貌似jd_cookie的长度太长会报错，JD_COOKIE的值为“pt_key=123;pt_pin=qaz;&pt_key=456;pt_pin=edc;”删掉几个cookie后就正常了，能否让main.py在根据pt_pin提取pt_key之前通过&分隔符分割后再提取就能解决了。

**Comment by icepage** [comment]
暂不支持不拆分JD_COOKIE，要先拆分后使用 @allonmymind
