### ISSUE TITLE
这个时什么问题阿！

### ISSUE THREAD

**Issue by sd462355991** [icepage/AutoUpdateJdCookie#82]
root@YQF:~# docker run -i -v /volume1/docker/AutoUpdateJdCookie-main/config.py:/app/config.py icepage/aujc:latest python main.py
2024-12-03 08:01:44.545 | INFO     | __main__:get_ql_api:487 - 开始获取QL登录态......
2024-12-03 08:01:44.546 | INFO     | __main__:get_ql_api:493 - 使用client_id和client_secret登录......
2024-12-03 08:01:44.650 | INFO     | __main__:get_ql_api:497 - client_id和client_secret正常可用......
2024-12-03 08:01:44.678 | INFO     | __main__:main:537 - 获取环境变量成功
2024-12-03 08:01:46.052 | INFO     | __main__:main:562 - 开始更新1598隐私68
2024-12-03 08:01:46.053 | INFO     | __main__:get_jd_pt_key:387 - 未配置代理
2024-12-03 08:01:58.299 | INFO     | __main__:auto_move_slide:71 - 第1次尝试自动移动滑块中...
2024-12-03 08:02:01.307 | INFO     | __main__:auto_move_slide:77 - 未找到小图,退出移动滑块
2024-12-03 08:02:02.970 | INFO     | __main__:auto_shape:135 - 第1次自动识别形状中...
2024-12-03 08:02:05.975 | INFO     | __main__:auto_shape:141 - 未找到形状图,退出识别状态
2024-12-03 08:02:06.992 | INFO     | __main__:get_jd_pt_key:463 - 等待获取cookie...
Traceback (most recent call last):
  File "/app/main.py", line 464, in get_jd_pt_key
    await page.wait_for_selector('#msShortcutMenu', state='visible', timeout=120000)
  File "/usr/local/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 7999, in wait_for_selector
    await self._impl_obj.wait_for_selector(
  File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_page.py", line 397, in wait_for_selector
    return await self._main_frame.wait_for_selector(**locals_to_params(locals()))
  File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 323, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
  File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Page.wait_for_selector: Timeout 120000ms exceeded.
Call log:
waiting for locator("#msShortcutMenu") to be visible

2024-12-03 08:04:07.221 | ERROR    | __main__:main:565 - 获取pt_key失败
2024-12-03 08:04:07.698 | INFO     | utils.tools:send_msg:332 - 发送消息到 https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=ac3e87e8-644隐私隐私隐私71f0bef, 响应:{'errcode': 0, 'errmsg': 'ok'}

**Comment by ywk1000** [comment]
我也是今天遇到这个问题了， 估计是时间延迟问题

**Comment by johnzon520** [comment]
今天也是同样的报错

**Comment by nethawkhu** [comment]
await page.wait_for_selector('#msShortcutMenu', state='visible', timeout=120000)

这个出错了，感觉是跳转页没有获取到？

**Comment by LouSpr** [comment]
新出了旋转图形，过不了验证了

**Comment by johnzon520** [comment]
windows 开浏览器模式正常

**Comment by nethawkhu** [comment]
修改了一下 user-agent ，可以工作了。
