### ISSUE TITLE
获取cookie失败，帮忙看看原因

### ISSUE THREAD

**Issue by superhdg** [icepage/AutoUpdateJdCookie#84]
docker计划任务运行容器，log如下

2024-12-06 00:01:42.767 | INFO     | main:get_jd_pt_key:393 - 未配置代理
Traceback (most recent call last):
  File "/app/main.py", line 405, in get_jd_pt_key
    await page.goto(jd_login_url)
  File "/usr/local/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 8810, in goto
    await self._impl_obj.goto(
  File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_page.py", line 524, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 145, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
  File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.
Call log:
navigating to "https://plogin.m.jd.com/login/login?appid=300&returnurl=https%3A%2F%2Fwq.jd.com%2Fpassport%2FLoginRedirect%3Fstate%3D1103073577433%26returnurl%3Dhttps%253A%252F%252Fhome.m.jd.com%252FmyJd%252Fhome.action&source=wq_passport", waiting until "load"

2024-12-06 00:06:20.717 | ERROR    | main:main:585 - 获取pt_key失败

**Comment by huxc573** [comment]
相同问题

**Comment by superhdg** [comment]
手动改了user-agent相关code解决

**Comment by icepage** [comment]
我将UA配置放出来

**Comment by hlw1995** [comment]
我改了ua还是一样
