### ISSUE TITLE
获取pt_key失败

### ISSUE THREAD

**Issue by huxc573** [icepage/AutoUpdateJdCookie#91]
![PixPin_2024-12-18_23-10-41](https://github.com/user-attachments/assets/734b904e-4718-47c3-b55f-529654820d82)

2024-12-18 23:05:23.648 | INFO     | __main__:get_jd_pt_key:393 - 未配置代理
2024-12-18 23:05:29.352 | INFO     | __main__:auto_move_slide:73 - 第1次尝试自动移动滑块中...
2024-12-18 23:05:32.367 | INFO     | __main__:auto_move_slide:79 - 未找到小图,退出移动滑块
2024-12-18 23:05:33.496 | INFO     | __main__:auto_shape:137 - 第1次自动识别形状中...
2024-12-18 23:05:36.509 | INFO     | __main__:auto_shape:143 - 未找到形状图,退出识别状态
2024-12-18 23:05:37.525 | INFO     | __main__:get_jd_pt_key:480 - 等待获取cookie...
Traceback (most recent call last):
  File "D:\Dev\Workspaces\Git\AutoUpdateJdCookie\main.py", line 481, in get_jd_pt_key
    await page.wait_for_selector('#msShortcutMenu', state='visible', timeout=120000)
  File "D:\Dev\Python\Env\Python3.10.5\lib\site-packages\playwright\async_api\_generated.py", line 8158, in wait_for_selector
    await self._impl_obj.wait_for_selector(
  File "D:\Dev\Python\Env\Python3.10.5\lib\site-packages\playwright\_impl\_page.py", line 426, in wait_for_selector
    return await self._main_frame.wait_for_selector(**locals_to_params(locals()))
  File "D:\Dev\Python\Env\Python3.10.5\lib\site-packages\playwright\_impl\_frame.py", line 323, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "D:\Dev\Python\Env\Python3.10.5\lib\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
  File "D:\Dev\Python\Env\Python3.10.5\lib\site-packages\playwright\_impl\_connection.py", line 520, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Page.wait_for_selector: Timeout 120000ms exceeded.
Call log:
waiting for locator("#msShortcutMenu") to be visible

2024-12-18 23:07:37.970 | ERROR    | __main__:main:585 - 获取pt_key失败

**Comment by realcsnake2023** [comment]
这也差不多是这样的问题，如果手机上看是没掉线的话，这个脚本也提示成功，但如果手机上看到是掉线的话，这个脚本也是失败

**Comment by hlw1995** [comment]
我也是这个问题。不知道怎么解决

**Comment by long1152153374** [comment]
这样的情况好久了，不知道咋回事

**Comment by long1152153374** [comment]
我也这样好久了，不知道怎么回事
2025-01-05 10:29:44.034 | INFO     | __main__:auto_move_slide:73 - 第1次尝试自动移动滑块中...

2025-01-05 10:29:47.040 | INFO     | __main__:auto_move_slide:79 - 未找到小图,退出移动滑块

2025-01-05 10:29:48.621 | INFO     | __main__:auto_shape:137 - 第1次自动识别形状中...

2025-01-05 10:29:51.623 | INFO     | __main__:auto_shape:143 - 未找到形状图,退出识别状态

2025-01-05 10:29:52.641 | INFO     | __main__:get_jd_pt_key:480 - 等待获取cookie...

**Comment by icepage** [comment]
![risk](https://github.com/user-attachments/assets/8a58f33b-e9e3-42e8-99a0-d7890b584e42)

原因如上图，大多针对新号，近期JD风控变严，本项目目前无解，建议：
1、自建jd_h5st_server，避免号黑，参考 https://thin-hill-428.notion.site/h5-116aae1a9ef8808784abe56ecc7b1ef1，
2、账号要实名，
3、耐心等待解封的那天。

**Comment by icepage** [comment]
亲测了一个号，昨天风险，今天却正常了，我也迷了

**Comment by long1152153374** [comment]
@icepage 一直都配置的有h5，没用的
